In [146]:
import numpy as np
import pandas as pd

added_stock = [2000,0,0,0,7000,0]
stocks_needed_week = 6000

n_days = len(added_stock)
stocks_needed = round(stocks_needed_week / n_days)

stocks_used = np.zeros(n_days)
stock_shortages = np.zeros(n_days)
stock_in_storage = np.zeros(n_days)

In [147]:
# calculate the day till next drop
reversed_added_stock = added_stock[::-1]

days_till_next_drop = np.zeros(n_days)

for i in range(n_days):
    if reversed_added_stock[i] == 0:
        days_till_next_drop[i] = days_till_next_drop[i - 1] + 1

for i in range(n_days):
    if days_till_next_drop[i] == 0:
        days_till_next_drop[i] = days_till_next_drop[i - 1] + 1

print("added_stock")
print(added_stock)

reversed_days_till_next_drop = days_till_next_drop[::-1]

print("reversed_days_till_next_drop")
print(reversed_days_till_next_drop)

added_stock
[2000, 0, 0, 0, 7000, 0]
reversed_days_till_next_drop
[4. 3. 2. 1. 2. 1.]


In [148]:
for i in range(n_days):
    # if we don't have the stock in storage
    if stock_in_storage[i] < stocks_needed:
        # check the newly added stock 
        # if we have enough 
        if added_stock[i] + stock_in_storage[i] >= stocks_needed:
            print("case1")
            # update the number of used item
            stocks_used[i] = min(stocks_needed,(added_stock[i] + stock_in_storage[i]) / reversed_days_till_next_drop[i]) 
            # update the number of item in storage
            stock_in_storage[i] = stock_in_storage[i] + added_stock[i] - stocks_used[i] 
        # if we don't have enogh items in the system
        else:
            print("case2")
            # send as much as we can
            stocks_used[i] = (added_stock[i] + stock_in_storage[i]) / reversed_days_till_next_drop[i] 
            # update the number shortage item
            stock_in_storage[i] = stocks_used[i] - stock_shortages[i]
            # add all the shortage into the stocks needed
            if n_days - i - 1 > 0:
                stocks_needed += round(stock_shortages[i] / (n_days - i - 1))
            else:
                stocks_needed += round(stock_shortages[i])
    # if we have enough items in the storage 
    else:
        print("case3")
        # update the number of stocks in storage
        stock_in_storage[i] = stock_in_storage[i] - stocks_needed + added_stock[i]
        # send everything we have
        stocks_used[i] = stocks_needed

    print(stocks_needed)
    print(stocks_used[i])



    stock_in_storage[i:] = stock_in_storage[i]

case1
1000
500.0
case3
1000
1000.0
case2
1000
250.0
case2
1000
250.0
case1
1000
1000.0
case3
1000
1000.0


In [149]:
print("stocks_used")
print(stocks_used)
print("stock_shortages")
print(stock_shortages)
print("stock_in_storage")
print(stock_in_storage)

stocks_used
[ 500. 1000.  250.  250. 1000. 1000.]
stock_shortages
[0. 0. 0. 0. 0. 0.]
stock_in_storage
[1500.  500.  250.  250. 6250. 5250.]
